# Generated by Django 5.1.1 on 2024-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_severity', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('CRITICAL', 'Critical'), ('MEDIUM', 'Medium')], default='LOW', max_length=10)),
                ('type_alert', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('push', 'Push Notification'), ('sms', 'SMS')], default='email', max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
