# Generated by Django 5.1.1 on 2024-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='rolones',
            field=models.CharField(choices=[('permi1', 'Permi1'), ('permi2', 'Permi2'), ('permi3', 'Permi3')], default='permi1', max_length=20),
        ),
    ]
