# Generated by Django 5.1.1 on 2024-09-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_role_user_rolones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rolones',
        ),
    ]
