# Generated by Django 5.1.1 on 2024-09-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('advanced', 'Advanced User'), ('basic', 'Basic User')], default='basic', max_length=20),
        ),
    ]
